/* eslint-disable */
// This file is intended to be generated by Supabase typegen.
// Keep it checked in so planner packages compile in isolation.
//
// Regenerate (example):
//   supabase gen types typescript --project-id "$SUPABASE_PROJECT_ID" --schema planner,public > packages/supabase/src/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  planner: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          home_city: string | null;
          typical_budget_range: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          home_city?: string | null;
          typical_budget_range?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          home_city?: string | null;
          typical_budget_range?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey';
            columns: ['id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      itineraries: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          start_date: string;
          end_date: string;
          preferences: Json;
          days: Json;
          estimated_budget_range: string | null;
          islands_covered: string[] | null;
          model_version: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          start_date: string;
          end_date: string;
          preferences: Json;
          days: Json;
          estimated_budget_range?: string | null;
          islands_covered?: string[] | null;
          model_version: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          start_date?: string;
          end_date?: string;
          preferences?: Json;
          days?: Json;
          estimated_budget_range?: string | null;
          islands_covered?: string[] | null;
          model_version?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'itineraries_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      generation_events: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'generation_events_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

