import React from "react";
import type { Itinerary } from "@andaman-planner/shared";
import { formatDisplayDate } from "@andaman-planner/shared";
import { DayCard } from "./DayCard.js";
import { clsx } from "clsx";

export interface ItineraryViewProps {
  itinerary: Itinerary;
  className?: string;
}

export function ItineraryView({ itinerary, className }: ItineraryViewProps) {
  return (
    <div className={clsx("ap-form", className)} style={{ gap: "1.5rem" }}>
      <div>
        <h2 style={{ fontSize: "1.5rem", fontWeight: 700, margin: 0 }}>
          {itinerary.name}
        </h2>
        <p style={{ color: "#64748b", margin: "0.25rem 0 0" }}>
          {formatDisplayDate(itinerary.startDate)} — {formatDisplayDate(itinerary.endDate)}
        </p>
      </div>

      <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem" }}>
        {itinerary.islandsCovered.map((island) => (
          <span key={island} className="ap-chip" data-selected="true">
            {island}
          </span>
        ))}
      </div>

      {itinerary.estimatedBudgetRange && (
        <div className="ap-card" style={{ background: "#f0fdfa" }}>
          <strong>Estimated Budget:</strong> {itinerary.estimatedBudgetRange}
        </div>
      )}

      <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
        {itinerary.days.map((day) => (
          <DayCard key={day.dayNumber} day={day} />
        ))}
      </div>

      <p style={{ fontSize: "0.75rem", color: "#94a3b8" }}>
        Generated by model: {itinerary.modelVersion}
      </p>
    </div>
  );
}
